wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.15
    start_time: 1669081975.597536
    t:
      1:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 13
      - 23
      4: 3.7.15
      5: 0.13.5
      8:
      - 5
